const actions = {
    ADD_MOVIE_WIN: 'ADD_MOVIE_WIN',
    ADD_MOVIE: 'ADD_MOVIE',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DEL_MOVIE: 'DEL_MOVIE',
    SORT_MOVIES: 'SORT_MOVIES',
    FILTER_MOVIES: 'FILTER_MOVIES',
    SEARCH_MOVIE: 'SEARCH_MOVIE',
    SEARCH_CLICK: 'SEARCH_CLICK',
    OPEN_CLICK: 'OPEN_CLICK',
    CLOSE_ADD_MOVIE: 'CLOSE_ADD_MOVIE',
    DELETE_CLICK:'DELETE_CLICK',
    EDIT_CLICK:'EDIT_CLICK',
    DDM_OPEN_CLICK:'DDM_OPEN_CLICK',
    MOVIE_CLICK:'MOVIE_CLICK',
    DEL_WINDOW_CLICK:'DEL_WINDOW_CLICK',
    DDM_CLOSE_CLICK:'DDM_CLOSE_CLICK',
    SORT_BY_RATING:'SORT_BY_RATING',
    POPULATE_MOVIE_LIST: 'POPULATE_MOVIE_LIST',
    POPULATE_MOVIE_LIST_ERR: 'POPULATE_MOVIE_LIST_ERR'
}

export default actions